### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by vincent-mayer** [cgtuebingen/SpatialDETR#2]
Hi,

I am trying to reproduce your results from the model checkpoint that offered. I am using your `docker` setup, which is why I'm confident that there are no difference in the environment. If I run eval again using:
```
python mmdetection3d/tools/test.py configs/submission/frozen_4/query_proj_value_proj.py query_proj_value_proj_epoch_24_release.pth --eval=bbox
```
I get as a result
```
mAP: 0.3149
mATE: 0.8375
mASE: 0.6275
mAOE: 0.4841
mAVE: 0.8124
mAAE: 0.2167
NDS: 0.3597
```
The NDS is lower by about .3 , but more importantly the `mASE` is significantly higher than what you had reported. Do you see any reason for this? I preprocessed the dataset using `mmdetetection3d` from the `v1.0rc1` tag.

**Comment by vincent-mayer** [comment]
There seems to be an inconsistency between the supplied checkpoint and the bounding box decoding. The following change in `detr3d/detr3d/core/bbox/util.py` fixed it for me: (uncommented is the original code and below that the change)
```python
    # size
    # l = normalized_bboxes[..., 3:4]
    # w = normalized_bboxes[..., 4:5]
    # h = normalized_bboxes[..., 5:6]

    l = normalized_bboxes[..., 3:4]
    h = normalized_bboxes[..., 4:5]
    w = normalized_bboxes[..., 5:6]
```

**Comment by SimonDoll** [comment]
Hi,
first of all sorry for my late response and thanks a lot for the interest in our work!
Unfortunately I've uploaded an older model + log to gdrive that used the old bbox definition (see https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/compatibility.md).
Thanks a lot for pointing this out and finding a fix @vincentmaye!
I will upload the correct model + log and update the  ```Readme.md``` accordingly. 
After the fix if should work with the original code.
Feel free to reopen in case of any further questions!
